// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQpPIn8vcoWrmccU9GJ_Ky-wEkQbz4OCE',
    appId: '1:687192945178:web:e394b2322c12619f3b97a3',
    messagingSenderId: '687192945178',
    projectId: 'dwa2y-d0eff',
    authDomain: 'dwa2y-d0eff.firebaseapp.com',
    storageBucket: 'dwa2y-d0eff.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClUfFyIuGPYHscZLpglHR36P_YC2mtLwE',
    appId: '1:687192945178:android:1e11c70c0750bfa43b97a3',
    messagingSenderId: '687192945178',
    projectId: 'dwa2y-d0eff',
    storageBucket: 'dwa2y-d0eff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvk2PpOZ7HC3k8ALaTo4kVc3tZXXqSCP0',
    appId: '1:687192945178:ios:c7495697953702bc3b97a3',
    messagingSenderId: '687192945178',
    projectId: 'dwa2y-d0eff',
    storageBucket: 'dwa2y-d0eff.appspot.com',
    androidClientId: '687192945178-pjl0l29c4ubltovkg7kd4nieb3rh1lba.apps.googleusercontent.com',
    iosClientId: '687192945178-oasblfparcqgvdqdhfoqcq6668r3uk8s.apps.googleusercontent.com',
    iosBundleId: 'com.example.dwa2y',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvk2PpOZ7HC3k8ALaTo4kVc3tZXXqSCP0',
    appId: '1:687192945178:ios:c7495697953702bc3b97a3',
    messagingSenderId: '687192945178',
    projectId: 'dwa2y-d0eff',
    storageBucket: 'dwa2y-d0eff.appspot.com',
    androidClientId: '687192945178-pjl0l29c4ubltovkg7kd4nieb3rh1lba.apps.googleusercontent.com',
    iosClientId: '687192945178-oasblfparcqgvdqdhfoqcq6668r3uk8s.apps.googleusercontent.com',
    iosBundleId: 'com.example.dwa2y',
  );
}
