// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIPJKnGLcFd4RoScPQujDqD-jv7mtH0jw',
    appId: '1:104216248112:web:4b9561dbcb7bc226f6d2f5',
    messagingSenderId: '104216248112',
    projectId: 'dwa2y-3cb9f',
    authDomain: 'dwa2y-3cb9f.firebaseapp.com',
    storageBucket: 'dwa2y-3cb9f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIc4_9-Y-2-7O_2JSkQ5mb2_Le9lI3Tvo',
    appId: '1:104216248112:android:f9dcb013a188856af6d2f5',
    messagingSenderId: '104216248112',
    projectId: 'dwa2y-3cb9f',
    storageBucket: 'dwa2y-3cb9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt-jc4Tr6ghPYhazwwTMlK8qou0W-hgK8',
    appId: '1:104216248112:ios:d585372d429cada9f6d2f5',
    messagingSenderId: '104216248112',
    projectId: 'dwa2y-3cb9f',
    storageBucket: 'dwa2y-3cb9f.appspot.com',
    iosClientId: '104216248112-9flikiicaclj101hmqt5ealfv1gorsni.apps.googleusercontent.com',
    iosBundleId: 'com.example.dwa2y',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt-jc4Tr6ghPYhazwwTMlK8qou0W-hgK8',
    appId: '1:104216248112:ios:d585372d429cada9f6d2f5',
    messagingSenderId: '104216248112',
    projectId: 'dwa2y-3cb9f',
    storageBucket: 'dwa2y-3cb9f.appspot.com',
    iosClientId: '104216248112-9flikiicaclj101hmqt5ealfv1gorsni.apps.googleusercontent.com',
    iosBundleId: 'com.example.dwa2y',
  );
}
